<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/ApiCore/Tests/Mocks/mocks.proto

namespace GPBMetadata\Tests\ApiCore\Tests\Mocks;

class Mocks
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a90020a2574657374732f417069436f72652f54657374732f4d6f636b73" .
            "2f6d6f636b732e70726f746f121a676f6f676c652e617069436f72652e74" .
            "657374732e6d6f636b7322340a0b4d6f636b5265717565737412120a0a70" .
            "6167655f746f6b656e18012001280912110a09706167655f73697a651802" .
            "20012804228c010a0f4d6f636b52657175657374426f6479120c0a046e61" .
            "6d65180120012809120e0a066e756d62657218022001280412160a0e7265" .
            "7065617465645f6669656c6418032003280912430a0e6e65737465645f6d" .
            "65737361676518042001280b322b2e676f6f676c652e617069436f72652e" .
            "74657374732e6d6f636b732e4d6f636b52657175657374426f6479620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

