<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/ApiCore/Tests/Mocks/mocks.proto

namespace GPBMetadata\Tests\ApiCore\Tests\Mocks;

class Mocks
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0add020a2574657374732f417069436f72652f54657374732f4d6f636b73" .
            "2f6d6f636b732e70726f746f121a676f6f676c652e617069636f72652e74" .
            "657374732e6d6f636b7322340a0b4d6f636b5265717565737412120a0a70" .
            "6167655f746f6b656e18012001280912110a09706167655f73697a651802" .
            "20012804222c0a0c4d6f636b526573706f6e7365120c0a046e616d651801" .
            "20012809120e0a066e756d626572180220012804228c010a0f4d6f636b52" .
            "657175657374426f6479120c0a046e616d65180120012809120e0a066e75" .
            "6d62657218022001280412160a0e72657065617465645f6669656c641803" .
            "2003280912430a0e6e65737465645f6d65737361676518042001280b322b" .
            "2e676f6f676c652e617069636f72652e74657374732e6d6f636b732e4d6f" .
            "636b52657175657374426f6479421dca021a476f6f676c655c417069436f" .
            "72655c54657374735c4d6f636b73620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

