<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/ApiCore/Tests/Mocks/mocks.proto

namespace GPBMetadata\Tests\ApiCore\Tests\Mocks;

class Mocks
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4020a0b6d6f636b732e70726f746f121a676f6f676c652e617069436f" .
            "72652e74657374732e6d6f636b7322340a0b4d6f636b5265717565737412" .
            "120a0a706167655f746f6b656e18012001280912110a09706167655f7369" .
            "7a65180220012804222c0a0c4d6f636b526573706f6e7365120c0a046e61" .
            "6d65180120012809120e0a066e756d626572180220012804228c010a0f4d" .
            "6f636b52657175657374426f6479120c0a046e616d65180120012809120e" .
            "0a066e756d62657218022001280412160a0e72657065617465645f666965" .
            "6c6418032003280912430a0e6e65737465645f6d65737361676518042001" .
            "280b322b2e676f6f676c652e617069436f72652e74657374732e6d6f636b" .
            "732e4d6f636b52657175657374426f6479620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

