<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ApiCore/Testing/mocks.proto

namespace GPBMetadata\ApiCore\Testing;

class Mocks
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\FieldMask::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91040a1b417069436f72652f54657374696e672f6d6f636b732e70726f" .
            "746f1216676f6f676c652e617069636f72652e74657374696e671a1e676f" .
            "6f676c652f70726f746f6275662f77726170706572732e70726f746f2234" .
            "0a0b4d6f636b5265717565737412120a0a706167655f746f6b656e180120" .
            "01280912110a09706167655f73697a65180220012804222c0a0c4d6f636b" .
            "526573706f6e7365120c0a046e616d65180120012809120e0a066e756d62" .
            "657218022001280422440a114d6f636b5061676564526573706f6e736512" .
            "160a0e7265736f75726365735f6c69737418012003280912170a0f6e6578" .
            "745f706167655f746f6b656e18022001280922ec010a0f4d6f636b526571" .
            "75657374426f6479120c0a046e616d65180120012809120e0a066e756d62" .
            "657218022001280412160a0e72657065617465645f6669656c6418032003" .
            "2809123f0a0e6e65737465645f6d65737361676518042001280b32272e67" .
            "6f6f676c652e617069636f72652e74657374696e672e4d6f636b52657175" .
            "657374426f6479122e0a0a6669656c645f6d61736b18052001280b321a2e" .
            "676f6f676c652e70726f746f6275662e4669656c644d61736b12320a0c73" .
            "7472696e675f76616c756518062001280b321c2e676f6f676c652e70726f" .
            "746f6275662e537472696e6756616c75654219ca0216476f6f676c655c41" .
            "7069436f72655c54657374696e67620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

